#!/bin/sh

set -eu

# creating gnome-initial-setup user if it isn't already there
if ! getent passwd gnome-initial-setup >/dev/null; then
        adduser --system --force-badname --quiet \
            --home /run/gnome-initial-setup/ --no-create-home \
            --shell /bin/false \
            gnome-initial-setup
fi

# remove old files in /etc/xdg/autostart
rm -f /etc/xdg/autostart/gnome-initial-setup-copy-worker.desktop
rm -f /etc/xdg/autostart/gnome-initial-setup-first-login.desktop
rm -f /etc/xdg/autostart/gnome-welcome-tour.desktop

#DEBHELPER#

exit 0
